# Site settings
title: TheS1tuation memes

collections:
  imgur:
    output: true
    sort_by: data_year
  pages:
    output: true

# Build settings
plugins:
  - jekyll-paginate-v2

# pagination
pagination:
  enabled: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Dockerfile
  - "*.sh"
  - scripts/
  - LICENSE
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
      permalink: /:path
      excerpt: ""
  - scope:
      path: "_imgur"
      type: "imgur"
    values:
      layout: "imgur"

kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
