name: Build the site
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo timedatectl set-timezone Asia/Kuala_Lumpur

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          python --version
          python scripts/fetch-imgur-data.py
          python scripts/parse-discord-data.py
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}

      - uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ hashFiles('**/Dockerfile') }}

      - name: Build the Docker image
        run: |
          if [[ "$(docker images --quiet $IMAGE_NAME 2> /dev/null)" == "" ]]; then
              docker build . --file Dockerfile --tag $IMAGE_NAME
          fi

          REPO_NAME=${GITHUB_REPOSITORY#*/}
          docker run --rm --volume "$PWD:/srv" $IMAGE_NAME jekyll build --baseurl "/${REPO_NAME}"
          sudo chown -R $(id -u):$(id -g) ./_site/
        env:
          IMAGE_NAME: jekyll-dev:latest

      - name: Sanitize referrer policy
        run: |
          curl -OL https://github.com/altbdoor/clean-links/releases/latest/download/clean-links-linux.tgz
          tar xzf clean-links-linux.tgz
          ./clean-links run --fix-all ./_site/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
